In [2]:
import numpy as np
    

In [5]:
A = np.

In [6]:
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
B = np.eye(A.shape[1],6)

In [14]:
print(B)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [12]:
A.shape[1]

4

In [16]:
type(B)

numpy.ndarray